// swift-tools-version: 6.0
// Generated by `shi-agency mcp new shi-mcp-template-reference` — W7 customer MCP scaffolder.
import PackageDescription

let package = Package(
    name: "shi-mcp-template-reference",
    platforms: [.macOS(.v14)],
    products: [
        .executable(name: "shi-mcp-template-reference", targets: ["shi-mcp-template-reference"]),
    ],
    dependencies: [
        .package(
            url: "https://github.com/FJ-Studios/SwiftMCP.git",
            from: "0.2.0"
        ),
    ],
    targets: [
        .executableTarget(
            name: "shi-mcp-template-reference",
            dependencies: [
                .product(name: "SwiftMCPServer", package: "SwiftMCP"),
                .target(name: "shi-mcp-template-referenceSampleTool"),
            ]
        ),
        .target(
            name: "shi-mcp-template-referenceSampleTool",
            dependencies: [
                .product(name: "SwiftMCPCore", package: "SwiftMCP"),
            ]
        ),
        .testTarget(
            name: "shi-mcp-template-referenceTests",
            dependencies: [
                "shi-mcp-template-referenceSampleTool",
                .product(name: "SwiftMCPCore", package: "SwiftMCP"),
                .product(name: "SwiftMCPServer", package: "SwiftMCP"),
                .product(name: "SwiftMCPTesting", package: "SwiftMCP"),
            ],
            path: "Tests/shi-mcp-template-referenceTests"
        ),
    ]
)