// Generated by `shi-agency mcp new shi-mcp-template-reference`.
// Entry point: register tools and start the MCP server over stdio.
import Foundation
import SwiftMCPServer
import shi_mcp_template_referenceSampleTool

// Compose: register all tools, then run.
let server = MCPServer(name: "shi-mcp-template-reference", version: "0.1.0")
try await server.register(PingTool())
await server.run(transport: .stdio)