// Generated by `shi-agency mcp new shi-mcp-template-reference`.
// shi-mcp-template-reference.swift — top-level composition module.
// Add domain-specific MCPTool conformers here and register them in main.swift.
import SwiftMCPServer
import shi_mcp_template_referenceSampleTool

// Re-export SampleTool so consumers of this module can discover it.
public typealias SamplePingTool = shi_mcp_template_referenceSampleTool.PingTool