// Generated by `shi-agency mcp new shi-mcp-template-reference`.
// SampleTool.swift — minimal MCPTool conformer to verify the scaffold.
// Replace or extend with customer-specific tool logic.
import Foundation
import SwiftMCPCore

// MARK: - PingTool

/// Minimal sample tool: echoes an optional message back to the caller.
/// Tool wire name: `shi-mcp-template-reference_ping`.
public struct PingTool: MCPTool, Sendable {

    public static let name = "shi-mcp-template-reference_ping"
    public static let description = "Ping the shi-mcp-template-reference MCP server. Returns the input message or 'pong'."
    public static let inputSchema: JSONValue = .object([
        "type": .string("object"),
        "properties": .object([
            "message": .object([
                "type": .string("string"),
                "description": .string("Optional message to echo back. Defaults to 'pong'."),
            ]),
        ]),
    ])

    public init() {}

    public func handle(_ params: JSONValue?, context: MCPContext) async throws -> JSONValue {
        let message = params?.objectValue?["message"]?.stringValue ?? "pong"
        return ToolResultBuilder.success(message)
    }
}